/**
 * document.ts — Assemble, validate, and read back the handoff document.
 *
 * The document has two parts. The frontmatter is generated by this extension,
 * so the session path and the session chain are always accurate. The body is
 * written by the agent (its final reply text), so the summary reflects what
 * the agent actually knows about the work in progress.
 */

import type { SessionEntry } from "@earendil-works/pi-coding-agent";

/** Machine-readable facts about the session a handoff was taken from. */
export interface HandoffMetadata {
  /** ISO timestamp of the handoff. */
  createdAt: string;
  /** Session file the handoff was taken from. */
  fromSession: string;
  /** Session id the handoff was taken from. */
  fromSessionId: string;
  /** Working directory of the handed-off session. */
  cwd: string;
  /** Ancestor session files, nearest first. */
  parentSessions: string[];
  /** Extra focus the user passed to `/handoff`, when any. */
  focus: string | undefined;
}

/** Outcome of validating an agent-written body. */
export interface HandoffValidation {
  ok: boolean;
  reason?: string;
}

/** Shortest body accepted as a real handoff (guards against a truncated reply). */
export const MIN_HANDOFF_BODY_LENGTH = 200;

/** A markdown heading line (`#` … `######`), used as a structural sanity check. */
const HEADING_PATTERN = /^#{1,6} \S/m;

/** Render the complete handoff document: generated frontmatter plus agent body. */
export function renderHandoffDocument(
  metadata: HandoffMetadata,
  body: string,
): string {
  return `${renderFrontmatter(metadata)}\n${body.trim()}\n`;
}

/** Render the YAML frontmatter block, including its delimiters. */
export function renderFrontmatter(metadata: HandoffMetadata): string {
  const lines: string[] = [
    "---",
    "handoff: true",
    `created: ${quote(metadata.createdAt)}`,
    `from_session: ${quote(metadata.fromSession)}`,
    `from_session_id: ${quote(metadata.fromSessionId)}`,
    `cwd: ${quote(metadata.cwd)}`,
  ];

  if (metadata.parentSessions.length === 0) {
    lines.push("parent_sessions: []");
  } else {
    lines.push("parent_sessions:");
    for (const parent of metadata.parentSessions) {
      lines.push(`  - ${quote(parent)}`);
    }
  }

  if (metadata.focus !== undefined && metadata.focus.length > 0) {
    lines.push(`focus: ${quote(metadata.focus)}`);
  }

  lines.push("---");
  return lines.join("\n");
}

/** Quote a scalar as a YAML double-quoted string (JSON escaping is compatible). */
function quote(value: string): string {
  return JSON.stringify(value);
}

/**
 * Check that an agent-written body looks like a handoff rather than a refusal,
 * a question, or a truncated reply.
 */
export function validateHandoffBody(body: string): HandoffValidation {
  const trimmed = body.trim();
  if (trimmed.length < MIN_HANDOFF_BODY_LENGTH) {
    return {
      ok: false,
      reason: `交接正文过短（${trimmed.length} 字符，至少需要 ${MIN_HANDOFF_BODY_LENGTH}）`,
    };
  }
  if (!HEADING_PATTERN.test(trimmed)) {
    return { ok: false, reason: "交接正文没有任何 markdown 标题" };
  }
  return { ok: true };
}

/**
 * Normalize an agent reply into a document body.
 *
 * Strips surrounding whitespace and unwraps a reply that the agent wrapped
 * wholesale in a fenced code block.
 */
export function normalizeHandoffBody(raw: string): string {
  const trimmed = raw.trim();
  const fence = /^```[^\n]*\n([\s\S]*?)\n?```$/.exec(trimmed);
  if (fence?.[1] !== undefined) return fence[1].trim();
  return trimmed;
}

/** The agent's final reply, plus how its run ended. */
export interface AssistantReply {
  /** Text of the last non-empty assistant reply, when the run produced one. */
  text: string | undefined;
  /** Stop reason of the last assistant message, when the branch has one. */
  stopReason: string | undefined;
}

/**
 * Find the agent's final reply in a session branch.
 *
 * The text is taken from the newest assistant message that carried text — a
 * run can end on a tool-only assistant message, and the summary is the last
 * thing the agent actually said.
 */
export function findLastAssistantReply(
  branch: readonly SessionEntry[],
): AssistantReply | undefined {
  let stopReason: string | undefined;
  let text: string | undefined;

  for (let index = branch.length - 1; index >= 0; index--) {
    const entry = branch[index];
    if (entry?.type !== "message" || entry.message.role !== "assistant")
      continue;

    if (stopReason === undefined) stopReason = entry.message.stopReason;
    if (text !== undefined) continue;

    const joined = entry.message.content
      .filter((part) => part.type === "text")
      .map((part) => part.text)
      .join("\n")
      .trim();
    if (joined.length > 0) text = joined;
  }

  if (stopReason === undefined && text === undefined) return undefined;
  return { text, stopReason };
}
